#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml>=6.0"]
# ///
"""Generate discovery files from SKILL.md files.

Scans plugins/*/skills/*/SKILL.md files and generates:
- AGENTS.md: Human + LLM readable skill discovery
- skills-index.json: Machine readable catalog
- skills/: Symlink directory for flat access

Usage:
    uv run scripts/build-discovery.py          # Generate all
    uv run scripts/build-discovery.py --check  # Validate only (CI mode)
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

import yaml


@dataclass
class SkillInfo:
    """Parsed skill metadata."""

    name: str
    description: str
    skill_path: Path
    plugin_name: str
    allowed_tools: list[str] | None = None


def parse_frontmatter(skill_md_path: Path) -> dict | None:
    """Parse YAML frontmatter from a SKILL.md file."""
    content = skill_md_path.read_text(encoding="utf-8")

    # Match frontmatter between --- markers
    match = re.match(r"^---\s*\n(.*?)\n---", content, re.DOTALL)
    if not match:
        return None

    try:
        return yaml.safe_load(match.group(1))
    except yaml.YAMLError as e:
        print(f"Error parsing frontmatter in {skill_md_path}: {e}", file=sys.stderr)
        return None


def discover_skills(plugins_dir: Path) -> list[SkillInfo]:
    """Discover all skills in plugins directory.

    Handles multiple nesting levels:
    - plugins/{plugin}/skills/{skill}/SKILL.md
    - plugins/{plugin}/skills/{category}/{skill}/SKILL.md
    - plugins/{plugin}/skills/SKILL.md (skill dir is skills/)
    """
    skills: list[SkillInfo] = []
    seen_names: dict[str, Path] = {}

    # Use recursive glob to find all SKILL.md files under skills/ directories
    for skill_md in sorted(plugins_dir.glob("*/skills/**/SKILL.md")):
        frontmatter = parse_frontmatter(skill_md)
        if not frontmatter:
            print(f"Warning: No valid frontmatter in {skill_md}", file=sys.stderr)
            continue

        name = frontmatter.get("name")
        description = frontmatter.get("description")

        if not name or not description:
            print(
                f"Warning: Missing name or description in {skill_md}",
                file=sys.stderr,
            )
            continue

        # Check for duplicate skill names
        if name in seen_names:
            print(
                f"Warning: Duplicate skill name '{name}' - "
                f"using {seen_names[name]}, ignoring {skill_md}",
                file=sys.stderr,
            )
            continue
        seen_names[name] = skill_md

        # Extract plugin name from path by finding 'skills' in the path
        # Path could be: plugins/{plugin}/skills/... or plugins/{plugin}/skills/{skill}/SKILL.md
        parts = skill_md.parts
        try:
            plugins_idx = parts.index("plugins")
            plugin_name = parts[plugins_idx + 1]
        except (ValueError, IndexError):
            print(f"Warning: Cannot determine plugin name for {skill_md}", file=sys.stderr)
            continue

        skill_dir = skill_md.parent

        skills.append(
            SkillInfo(
                name=name,
                description=description,
                skill_path=skill_dir,
                plugin_name=plugin_name,
                allowed_tools=frontmatter.get("allowed-tools"),
            )
        )

    return skills


def generate_agents_md(skills: list[SkillInfo], version: str = "1.0.0") -> str:
    """Generate AGENTS.md content."""
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d")

    lines = [
        "# Trail of Bits Skills",
        "",
        f"Version: {version}",
        f"Generated: {timestamp}",
        "",
        "This file is auto-generated by `scripts/build-discovery.py`.",
        "It provides skill discovery for AI coding agents (OpenSkills, Cursor, Windsurf, etc.).",
        "",
        "## Available Skills",
        "",
    ]

    # Group skills by plugin
    by_plugin: dict[str, list[SkillInfo]] = {}
    for skill in skills:
        by_plugin.setdefault(skill.plugin_name, []).append(skill)

    for plugin_name in sorted(by_plugin.keys()):
        plugin_skills = by_plugin[plugin_name]
        lines.append(f"### Plugin: {plugin_name}")
        lines.append("")

        for skill in sorted(plugin_skills, key=lambda s: s.name):
            lines.append(f"#### {skill.name}")
            lines.append(f"**Description:** {skill.description}")
            lines.append(f"**Path:** `skills/{skill.name}/`")
            if skill.allowed_tools:
                lines.append(f"**Allowed Tools:** {', '.join(skill.allowed_tools)}")
            lines.append("")

    return "\n".join(lines)


def generate_skills_index(skills: list[SkillInfo], version: str = "1.0.0") -> dict:
    """Generate skills-index.json content."""
    timestamp = datetime.now(UTC).isoformat()

    return {
        "version": version,
        "generated": timestamp,
        "skills": [
            {
                "name": s.name,
                "description": s.description,
                "path": f"skills/{s.name}",
                "plugin": s.plugin_name,
                "source_path": str(s.skill_path.relative_to(Path.cwd())),
                **({"allowed_tools": s.allowed_tools} if s.allowed_tools else {}),
            }
            for s in sorted(skills, key=lambda x: x.name)
        ],
    }


def create_symlinks(skills: list[SkillInfo], skills_dir: Path) -> list[str]:
    """Create symlinks in skills/ directory.

    Returns list of errors if any.
    """
    errors: list[str] = []

    # Create skills directory if it doesn't exist
    skills_dir.mkdir(exist_ok=True)

    # Track which symlinks we want to exist
    expected_symlinks = {s.name for s in skills}

    # Remove stale symlinks
    for item in skills_dir.iterdir():
        if item.is_symlink() and item.name not in expected_symlinks:
            item.unlink()

    # Create/update symlinks
    for skill in skills:
        symlink_path = skills_dir / skill.name
        # Calculate relative path from skills/{name} to actual skill directory
        target = os.path.relpath(skill.skill_path, symlink_path.parent)

        if symlink_path.is_symlink():
            current_target = os.readlink(symlink_path)
            if current_target == target:
                continue  # Already correct
            symlink_path.unlink()
        elif symlink_path.exists():
            errors.append(f"Cannot create symlink {symlink_path}: path exists and is not a symlink")
            continue

        symlink_path.symlink_to(target)

    return errors


def validate_check_mode(
    skills: list[SkillInfo],
    agents_md_path: Path,
    index_json_path: Path,
    skills_dir: Path,
) -> list[str]:
    """Validate that generated files match what's on disk."""
    errors: list[str] = []

    # Check AGENTS.md
    if not agents_md_path.exists():
        errors.append(f"Missing {agents_md_path}")
    else:
        expected = generate_agents_md(skills)
        actual = agents_md_path.read_text(encoding="utf-8")
        # Compare ignoring timestamp line
        expected_lines = [
            line for line in expected.splitlines() if not line.startswith("Generated:")
        ]
        actual_lines = [line for line in actual.splitlines() if not line.startswith("Generated:")]
        if expected_lines != actual_lines:
            errors.append(
                f"{agents_md_path} is out of date. Run: uv run scripts/build-discovery.py"
            )

    # Check skills-index.json
    if not index_json_path.exists():
        errors.append(f"Missing {index_json_path}")
    else:
        expected = generate_skills_index(skills)
        actual = json.loads(index_json_path.read_text(encoding="utf-8"))
        # Compare ignoring generated timestamp
        expected_comparable = {k: v for k, v in expected.items() if k != "generated"}
        actual_comparable = {k: v for k, v in actual.items() if k != "generated"}
        if expected_comparable != actual_comparable:
            errors.append(
                f"{index_json_path} is out of date. Run: uv run scripts/build-discovery.py"
            )

    # Check symlinks
    if not skills_dir.exists():
        errors.append(f"Missing {skills_dir} directory")
    else:
        expected_names = {s.name for s in skills}
        actual_symlinks = {
            item.name for item in skills_dir.iterdir() if item.is_symlink() or item.is_dir()
        }

        missing = expected_names - actual_symlinks
        if missing:
            errors.append(
                f"Missing symlinks in {skills_dir}: {', '.join(sorted(missing))}. "
                f"Run: uv run scripts/build-discovery.py"
            )

        extra = actual_symlinks - expected_names
        if extra:
            errors.append(f"Extra items in {skills_dir}: {', '.join(sorted(extra))}")

    return errors


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate discovery files from SKILL.md files",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate only, don't write files (for CI)",
    )
    parser.add_argument(
        "--version",
        default="1.0.0",
        help="Version string for generated files (default: 1.0.0)",
    )
    args = parser.parse_args()

    # Paths
    root = Path.cwd()
    plugins_dir = root / "plugins"
    skills_dir = root / "skills"
    agents_md_path = root / "AGENTS.md"
    index_json_path = root / "skills-index.json"

    if not plugins_dir.exists():
        print(f"Error: {plugins_dir} not found", file=sys.stderr)
        return 1

    # Discover skills
    skills = discover_skills(plugins_dir)
    print(f"Found {len(skills)} skills across {len(set(s.plugin_name for s in skills))} plugins")

    if args.check:
        # Validation mode
        errors = validate_check_mode(skills, agents_md_path, index_json_path, skills_dir)
        if errors:
            print("\nValidation errors:", file=sys.stderr)
            for error in errors:
                print(f"  - {error}", file=sys.stderr)
            return 1
        print("All discovery files are up to date.")
        return 0

    # Generate mode
    errors: list[str] = []

    # Create symlinks
    symlink_errors = create_symlinks(skills, skills_dir)
    errors.extend(symlink_errors)
    if not symlink_errors:
        print(f"Created/updated symlinks in {skills_dir}/")

    # Generate AGENTS.md
    agents_content = generate_agents_md(skills, args.version)
    agents_md_path.write_text(agents_content, encoding="utf-8")
    print(f"Generated {agents_md_path}")

    # Generate skills-index.json
    index_content = generate_skills_index(skills, args.version)
    index_json_path.write_text(
        json.dumps(index_content, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"Generated {index_json_path}")

    if errors:
        print("\nErrors:", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
